name: Android Build

on:
  push:
    branches:
      - main
      - develop
      - ui
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  assemble-debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK packages
        run: sdkmanager "platforms;android-36" "build-tools;36.0.0"

      - name: Assemble debug APK
        run: |
          chmod +x ./gradlew
          ./gradlew assembleDebug
          mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/SMS-SENDER.apk

      - name: Upload debug APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SMS-SENDER.apk
          path: app/build/outputs/apk/debug/SMS-SENDER.apk

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: app/build/outputs/apk/debug/SMS-SENDER.apk
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
